spring.application.name=cart
spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.password=${REDIS_PASSWORD}
spring.data.redis.port=${REDIS_PORT:6379}

server.servlet.context-path=/shopping-cart
springdoc.swagger-ui.path=/docs

# Feign client
service.catalog.url=http://localhost:8081