spring.application.name=cart
spring.data.redis.host=localhost
spring.data.redis.password=securepassword
spring.data.redis.port=6379

server.servlet.context-path=/shopping-cart
springdoc.swagger-ui.path=/docs